// UN recognized countries (193 member states + 2 observer states)
export const UN_COUNTRIES = [
  "af",
  "al",
  "dz",
  "ad",
  "ao",
  "ag",
  "ar",
  "am",
  "au",
  "at",
  "az",
  "bs",
  "bh",
  "bd",
  "bb",
  "by",
  "be",
  "bz",
  "bj",
  "bt",
  "bo",
  "ba",
  "bw",
  "br",
  "bn",
  "bg",
  "bf",
  "bi",
  "cv",
  "kh",
  "cm",
  "ca",
  "cf",
  "td",
  "cl",
  "cn",
  "co",
  "km",
  "cg",
  "cd",
  "cr",
  "ci",
  "hr",
  "cu",
  "cy",
  "cz",
  "dk",
  "dj",
  "dm",
  "do",
  "ec",
  "eg",
  "sv",
  "gq",
  "er",
  "ee",
  "et",
  "fj",
  "fi",
  "fr",
  "ga",
  "gm",
  "ge",
  "de",
  "gh",
  "gr",
  "gd",
  "gt",
  "gn",
  "gw",
  "gy",
  "ht",
  "hn",
  "hu",
  "is",
  "in",
  "id",
  "ir",
  "iq",
  "ie",
  "il",
  "it",
  "jm",
  "jp",
  "jo",
  "kz",
  "ke",
  "ki",
  "kp",
  "kr",
  "kw",
  "kg",
  "la",
  "lv",
  "lb",
  "ls",
  "lr",
  "ly",
  "li",
  "lt",
  "lu",
  "mg",
  "mw",
  "my",
  "mv",
  "ml",
  "mt",
  "mh",
  "mr",
  "mu",
  "mx",
  "fm",
  "md",
  "mc",
  "mn",
  "me",
  "ma",
  "mz",
  "mm",
  "na",
  "nr",
  "np",
  "nl",
  "nz",
  "ni",
  "ne",
  "ng",
  "mk",
  "no",
  "om",
  "pk",
  "pw",
  "pa",
  "pg",
  "py",
  "pe",
  "ph",
  "pl",
  "pt",
  "qa",
  "ro",
  "ru",
  "rw",
  "kn",
  "lc",
  "vc",
  "ws",
  "sm",
  "st",
  "sa",
  "sn",
  "rs",
  "sc",
  "sl",
  "sg",
  "sk",
  "si",
  "sb",
  "so",
  "za",
  "ss",
  "es",
  "lk",
  "sd",
  "sr",
  "sz",
  "se",
  "ch",
  "sy",
  "tj",
  "tz",
  "th",
  "tl",
  "tg",
  "to",
  "tt",
  "tn",
  "tr",
  "tm",
  "tv",
  "ug",
  "ua",
  "ae",
  "gb",
  "us",
  "uy",
  "uz",
  "vu",
  "ve",
  "vn",
  "ye",
  "zm",
  "zw",
  // Observer states
  "va",
  "ps",
] as const;

export const CONTINENTS = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
] as const;

export type QuizLength = number | "all";
export type CountryFilter = "un" | "all";

export type CountryInfo = {
  name: string;
  altNames?: string[];
  capital?: string; // Optional if not all countries have a known capital
  continent?: string; // Optional
  languages?: string[]; // Optional, array of strings for multiple languages
  currency?: { name: string; code: string; symbol: string };
  subregion?: string;
  areaKm2?: number;
  tld?: string;
};
export const COUNTRY_DATA: { [key: string]: CountryInfo } = {
  aq: {
    name: "Antarctica",
    altNames: ["Antarctica", "Antarctic Treaty Area"],
    continent: "Antarctica",
    languages: [],
    areaKm2: 14000000,
    tld: ".aq",
  },
  ad: {
    name: "Andorra",
    capital: "Andorra la Vella",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Catalan"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 468,
    tld: ".ad",
  },
  ae: {
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: {
      name: "United Arab Emirates Dirham",
      code: "AED",
      symbol: "د.إ",
    },
    areaKm2: 83600,
    tld: ".ae",
  },
  af: {
    name: "Afghanistan",
    capital: "Kabul",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Dari", "Pashto"],
    currency: { name: "Afghan Afghani", code: "AFN", symbol: "؋" },
    areaKm2: 652864,
    tld: ".af",
  },
  ag: {
    name: "Antigua and Barbuda",
    altNames: ["Antigua & Barbuda"],
    capital: "Saint John's",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 442,
    tld: ".ag",
  },
  ai: {
    name: "Anguilla",
    capital: "The Valley",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 91,
    tld: ".ai",
  },
  al: {
    name: "Albania",
    capital: "Tirana",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Albanian"],
    currency: { name: "Albanian Lek", code: "ALL", symbol: "L" },
    areaKm2: 28748,
    tld: ".al",
  },
  am: {
    name: "Armenia",
    capital: "Yerevan",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Armenian"],
    currency: { name: "Armenian Dram", code: "AMD", symbol: "֏" },
    areaKm2: 29743,
    tld: ".am",
  },
  ao: {
    name: "Angola",
    capital: "Luanda",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["Portuguese"],
    currency: { name: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
    areaKm2: 1246700,
    tld: ".ao",
  },
  ar: {
    name: "Argentina",
    capital: "Buenos Aires",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Argentine Peso", code: "ARS", symbol: "$" },
    areaKm2: 2780400,
    tld: ".ar",
  },
  as: {
    name: "American Samoa",
    capital: "Pago Pago",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["English", "Samoan"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 199,
    tld: ".as",
  },
  at: {
    name: "Austria",
    capital: "Vienna",
    continent: "Europe",
    subregion: "Central Europe",
    languages: ["German"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 83871,
    tld: ".at",
  },
  au: {
    name: "Australia",
    capital: "Canberra",
    continent: "Oceania",
    subregion: "Australia and New Zealand",
    languages: ["English"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 7692024,
    tld: ".au",
  },
  aw: {
    name: "Aruba",
    capital: "Oranjestad",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Dutch", "Papiamento"],
    currency: { name: "Aruban Florin", code: "AWG", symbol: "ƒ" },
    areaKm2: 180,
    tld: ".aw",
  },
  ax: {
    name: "Åland Islands",
    altNames: ["Aland Islands", "Aland"],
    capital: "Mariehamn",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Swedish"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 1580,
    tld: ".ax",
  },
  az: {
    name: "Azerbaijan",
    capital: "Baku",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Azerbaijani"],
    currency: { name: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
    areaKm2: 86600,
    tld: ".az",
  },
  ba: {
    name: "Bosnia and Herzegovina",
    altNames: ["Bosnia & Herzegovina", "Bosnia-Herzegovina", "Bosnia"],
    capital: "Sarajevo",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Bosnian", "Croatian", "Serbian"],
    currency: {
      name: "Bosnia and Herzegovina Convertible Mark",
      code: "BAM",
      symbol: "KM",
    },
    areaKm2: 51209,
    tld: ".ba",
  },
  bb: {
    name: "Barbados",
    capital: "Bridgetown",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Barbadian Dollar", code: "BBD", symbol: "$" },
    areaKm2: 430,
    tld: ".bb",
  },
  bd: {
    name: "Bangladesh",
    capital: "Dhaka",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Bengali"],
    currency: { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
    areaKm2: 147570,
    tld: ".bd",
  },
  be: {
    name: "Belgium",
    capital: "Brussels",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["Dutch", "French", "German"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 30528,
    tld: ".be",
  },
  bf: {
    name: "Burkina Faso",
    capital: "Ouagadougou",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 272967,
    tld: ".bf",
  },
  bg: {
    name: "Bulgaria",
    capital: "Sofia",
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Bulgarian"],
    currency: { name: "Bulgarian Lev", code: "BGN", symbol: "лв" },
    areaKm2: 110879,
    tld: ".bg",
  },
  bh: {
    name: "Bahrain",
    capital: "Manama",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
    areaKm2: 765,
    tld: ".bh",
  },
  bi: {
    name: "Burundi",
    capital: "Gitega",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Kirundi", "French"],
    currency: { name: "Burundian Franc", code: "BIF", symbol: "Fr" },
    areaKm2: 27834,
    tld: ".bi",
  },
  bj: {
    name: "Benin",
    capital: "Porto-Novo",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 112622,
    tld: ".bj",
  },
  bl: {
    name: "Saint Barthélemy",
    altNames: ["Saint Barthelemy", "St. Barthelemy", "St. Barthélemy"],
    capital: "Gustavia",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 21,
    tld: ".bl",
  },
  bm: {
    name: "Bermuda",
    capital: "Hamilton",
    continent: "North America",
    subregion: "Northern America",
    languages: ["English"],
    currency: { name: "Bermudian Dollar", code: "BMD", symbol: "$" },
    areaKm2: 54,
    tld: ".bm",
  },
  bn: {
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Malay"],
    currency: { name: "Brunei Dollar", code: "BND", symbol: "$" },
    areaKm2: 5765,
    tld: ".bn",
  },
  bo: {
    name: "Bolivia",
    capital: "Sucre (constitutional), La Paz (administrative)",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish", "Quechua", "Aymara"],
    currency: { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs." },
    areaKm2: 1098581,
    tld: ".bo",
  },
  bq: {
    name: "Caribbean Netherlands",
    capital: "Kralendijk (Bonaire)",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Dutch"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 328,
    tld: ".bq",
  },
  br: {
    name: "Brazil",
    capital: "Brasília",
    continent: "South America",
    subregion: "South America",
    languages: ["Portuguese"],
    currency: { name: "Brazilian Real", code: "BRL", symbol: "R$" },
    areaKm2: 8515767,
    tld: ".br",
  },
  bs: {
    name: "Bahamas",
    capital: "Nassau",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Bahamian Dollar", code: "BSD", symbol: "$" },
    areaKm2: 13943,
    tld: ".bs",
  },
  bt: {
    name: "Bhutan",
    capital: "Thimphu",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Dzongkha"],
    currency: { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
    areaKm2: 38394,
    tld: ".bt",
  },
  bw: {
    name: "Botswana",
    capital: "Gaborone",
    continent: "Africa",
    subregion: "Southern Africa",
    languages: ["English", "Setswana"],
    currency: { name: "Botswana Pula", code: "BWP", symbol: "P" },
    areaKm2: 581730,
    tld: ".bw",
  },
  by: {
    name: "Belarus",
    capital: "Minsk",
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Belarusian", "Russian"],
    currency: { name: "Belarusian Ruble", code: "BYN", symbol: "Br" },
    areaKm2: 207600,
    tld: ".by",
  },
  bz: {
    name: "Belize",
    capital: "Belmopan",
    continent: "North America",
    subregion: "Central America",
    languages: ["English"],
    currency: { name: "Belize Dollar", code: "BZD", symbol: "$" },
    areaKm2: 22966,
    tld: ".bz",
  },
  ca: {
    name: "Canada",
    capital: "Ottawa",
    continent: "North America",
    subregion: "Northern America",
    languages: ["English", "French"],
    currency: { name: "Canadian Dollar", code: "CAD", symbol: "$" },
    areaKm2: 9984670,
    tld: ".ca",
  },
  cc: {
    name: "Cocos (Keeling) Islands",
    altNames: ["Cocos Islands", "Keeling Islands"],
    capital: "West Island",
    continent: "Asia",
    subregion: "Australia and New Zealand",
    languages: ["English", "Malay"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 14,
    tld: ".cc",
  },
  cd: {
    name: "DR Congo",
    altNames: [
      "Democratic Republic of the Congo",
      "DRC",
      "Congo-Kinshasa",
      "Zaire",
    ],
    capital: "Kinshasa",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["French"],
    currency: { name: "Congolese Franc", code: "CDF", symbol: "FC" },
    areaKm2: 2344858,
    tld: ".cd",
  },
  cf: {
    name: "Central African Republic",
    capital: "Bangui",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["French", "Sango"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 622984,
    tld: ".cf",
  },
  cg: {
    name: "Republic of the Congo",
    altNames: ["Congo", "Congo-Brazzaville"],
    capital: "Brazzaville",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["French"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 342000,
    tld: ".cg",
  },
  ch: {
    name: "Switzerland",
    capital: "Bern",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["German", "French", "Italian", "Romansh"],
    currency: { name: "Swiss Franc", code: "CHF", symbol: "Fr." },
    areaKm2: 41284,
    tld: ".ch",
  },
  ci: {
    name: "Côte d'Ivoire (Ivory Coast)",
    altNames: ["Cote d'Ivoire", "Ivory Coast"],
    capital: "Yamoussoukro",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 322463,
    tld: ".ci",
  },
  ck: {
    name: "Cook Islands",
    capital: "Avarua",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["English", "Cook Islands Māori"],
    currency: { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    areaKm2: 236,
    tld: ".ck",
  },
  cl: {
    name: "Chile",
    capital: "Santiago",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Chilean Peso", code: "CLP", symbol: "$" },
    areaKm2: 756102,
    tld: ".cl",
  },
  cm: {
    name: "Cameroon",
    capital: "Yaoundé",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["English", "French"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 475442,
    tld: ".cm",
  },
  cn: {
    name: "China",
    capital: "Beijing",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Mandarin"],
    currency: { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
    areaKm2: 9706961,
    tld: ".cn",
  },
  co: {
    name: "Colombia",
    capital: "Bogotá",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Colombian Peso", code: "COP", symbol: "$" },
    areaKm2: 1141748,
    tld: ".co",
  },
  cr: {
    name: "Costa Rica",
    capital: "San José",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Costa Rican Colón", code: "CRC", symbol: "₡" },
    areaKm2: 51100,
    tld: ".cr",
  },
  cu: {
    name: "Cuba",
    capital: "Havana",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Spanish"],
    currency: { name: "Cuban Peso", code: "CUP", symbol: "$" },
    areaKm2: 109884,
    tld: ".cu",
  },
  cv: {
    name: "Cape Verde",
    capital: "Praia",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["Portuguese"],
    currency: { name: "Cape Verdean Escudo", code: "CVE", symbol: "$" },
    areaKm2: 4033,
    tld: ".cv",
  },
  cw: {
    name: "Curaçao",
    altNames: ["Curacao"],
    capital: "Willemstad",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Dutch", "Papiamento", "English"],
    currency: {
      name: "Netherlands Antillean Guilder",
      code: "ANG",
      symbol: "ƒ",
    },
    areaKm2: 444,
    tld: ".cw",
  },
  cx: {
    name: "Christmas Island",
    capital: "Flying Fish Cove",
    continent: "Asia",
    subregion: "Australia and New Zealand",
    languages: ["English"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 135,
    tld: ".cx",
  },
  cy: {
    name: "Cyprus",
    capital: "Nicosia",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Greek", "Turkish"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 9251,
    tld: ".cy",
  },
  cz: {
    name: "Czechia",
    altNames: ["Czechia", "Czech Republic", "Czech"],
    capital: "Prague",
    continent: "Europe",
    subregion: "Central Europe",
    languages: ["Czech"],
    currency: { name: "Czech Koruna", code: "CZK", symbol: "Kč" },
    areaKm2: 78865,
    tld: ".cz",
  },
  de: {
    name: "Germany",
    capital: "Berlin",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["German"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 357114,
    tld: ".de",
  },
  dj: {
    name: "Djibouti",
    capital: "Djibouti City",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Arabic", "French"],
    currency: { name: "Djiboutian Franc", code: "DJF", symbol: "Fr" },
    areaKm2: 23200,
    tld: ".dj",
  },
  dk: {
    name: "Denmark",
    capital: "Copenhagen",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Danish"],
    currency: { name: "Danish Krone", code: "DKK", symbol: "kr" },
    areaKm2: 43094,
    tld: ".dk",
  },
  dm: {
    name: "Dominica",
    capital: "Roseau",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 751,
    tld: ".dm",
  },
  do: {
    name: "Dominican Republic",
    capital: "Santo Domingo",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Spanish"],
    currency: { name: "Dominican Peso", code: "DOP", symbol: "RD$" },
    areaKm2: 48671,
    tld: ".do",
  },
  dz: {
    name: "Algeria",
    capital: "Algiers",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic", "Berber"],
    currency: { name: "Algerian Dinar", code: "DZD", symbol: "د.ج" },
    areaKm2: 2381741,
    tld: ".dz",
  },
  ec: {
    name: "Ecuador",
    capital: "Quito",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 283561,
    tld: ".ec",
  },
  ee: {
    name: "Estonia",
    capital: "Tallinn",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Estonian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 45227,
    tld: ".ee",
  },
  eg: {
    name: "Egypt",
    capital: "Cairo",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    currency: { name: "Egyptian Pound", code: "EGP", symbol: "E£" },
    areaKm2: 1010408,
    tld: ".eg",
  },
  eh: {
    name: "Western Sahara",
    capital: "Laayoune, El Aaiún (disputed)",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    currency: { name: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
    areaKm2: 266000,
    tld: ".eh",
  },
  er: {
    name: "Eritrea",
    capital: "Asmara",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Tigrinya", "Arabic", "English"],
    currency: { name: "Eritrean Nakfa", code: "ERN", symbol: "Nfk" },
    areaKm2: 117600,
    tld: ".er",
  },
  es: {
    name: "Spain",
    capital: "Madrid",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Spanish"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 505992,
    tld: ".es",
  },
  et: {
    name: "Ethiopia",
    capital: "Addis Ababa",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Amharic"],
    currency: { name: "Ethiopian Birr", code: "ETB", symbol: "Br" },
    areaKm2: 1104300,
    tld: ".et",
  },
  fi: {
    name: "Finland",
    capital: "Helsinki",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Finnish", "Swedish"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 338424,
    tld: ".fi",
  },
  fj: {
    name: "Fiji",
    capital: "Suva",
    continent: "Oceania",
    subregion: "Melanesia",
    languages: ["English", "Fijian", "Fiji Hindi"],
    currency: { name: "Fijian Dollar", code: "FJD", symbol: "$" },
    areaKm2: 18272,
    tld: ".fj",
  },
  fk: {
    name: "Falkland Islands",
    altNames: ["Malvinas", "Falkland Islands (Malvinas)"],
    capital: "Stanley",
    continent: "South America",
    subregion: "South America",
    languages: ["English"],
    currency: { name: "Falkland Islands Pound", code: "FKP", symbol: "£" },
    areaKm2: 12173,
    tld: ".fk",
  },
  fm: {
    name: "Micronesia",
    altNames: [
      "Micronesia (Federated States of)",
      "Micronesia",
      "Federated States of Micronesia",
    ],
    capital: "Palikir",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 702,
    tld: ".fm",
  },
  fo: {
    name: "Faroe Islands",
    capital: "Tórshavn",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Faroese", "Danish"],
    currency: { name: "Danish Krone", code: "DKK", symbol: "kr" },
    areaKm2: 1393,
    tld: ".fo",
  },
  fr: {
    name: "France",
    capital: "Paris",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 643801,
    tld: ".fr",
  },
  ga: {
    name: "Gabon",
    capital: "Libreville",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["French"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 267668,
    tld: ".ga",
  },
  gb: {
    name: "United Kingdom",
    altNames: [
      "United Kingdom",
      "UK",
      "U.K.",
      "Great Britain",
      "Britain",
      "England",
      "Scotland",
      "Wales",
      "Northern Ireland",
    ],
    capital: "London",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English"],
    currency: { name: "Pound Sterling", code: "GBP", symbol: "£" },
    areaKm2: 242495,
    tld: ".uk",
  },
  gd: {
    name: "Grenada",
    capital: "St. George's",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 344,
    tld: ".gd",
  },
  ge: {
    name: "Georgia",
    altNames: ["Georgia_country"],
    capital: "Tbilisi",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Georgian"],
    currency: { name: "Georgian Lari", code: "GEL", symbol: "₾" },
    areaKm2: 69700,
    tld: ".ge",
  },
  gf: {
    name: "French Guiana",
    capital: "Cayenne",
    continent: "South America",
    subregion: "South America",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 83534,
    tld: ".gf",
  },
  gg: {
    name: "Guernsey",
    capital: "Saint Peter Port",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Guernésiais", "French"],
    currency: { name: "Pound Sterling", code: "GBP", symbol: "£" },
    areaKm2: 78,
    tld: ".gg",
  },
  gh: {
    name: "Ghana",
    capital: "Accra",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
    areaKm2: 238533,
    tld: ".gh",
  },
  gi: {
    name: "Gibraltar",
    capital: "Gibraltar",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["English"],
    currency: { name: "Gibraltar Pound", code: "GIP", symbol: "£" },
    areaKm2: 6.5,
    tld: ".gi",
  },
  gl: {
    name: "Greenland",
    capital: "Nuuk",
    continent: "North America",
    subregion: "Northern America",
    languages: ["Greenlandic", "Danish"],
    currency: { name: "Danish Krone", code: "DKK", symbol: "kr" },
    areaKm2: 2166086,
    tld: ".gl",
  },
  gm: {
    name: "Gambia",
    capital: "Banjul",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Gambian Dalasi", code: "GMD", symbol: "D" },
    areaKm2: 10689,
    tld: ".gm",
  },
  gn: {
    name: "Guinea",
    capital: "Conakry",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "Guinean Franc", code: "GNF", symbol: "Fr" },
    areaKm2: 245857,
    tld: ".gn",
  },
  gp: {
    name: "Guadeloupe",
    capital: "Basse-Terre",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 1628,
    tld: ".gp",
  },
  gq: {
    name: "Equatorial Guinea",
    capital: "Malabo",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["Spanish", "French", "Portuguese"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 28051,
    tld: ".gq",
  },
  gr: {
    name: "Greece",
    capital: "Athens",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Greek"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 131990,
    tld: ".gr",
  },
  gs: {
    name: "South Georgia",
    capital: "King Edward Point",
    continent: "Antarctica",
    subregion: "South America",
    languages: ["English"],
    currency: { name: "Pound Sterling", code: "GBP", symbol: "£" },
    areaKm2: 3903,
    tld: ".gs",
  },
  gt: {
    name: "Guatemala",
    capital: "Guatemala City",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
    areaKm2: 108889,
    tld: ".gt",
  },
  gu: {
    name: "Guam",
    capital: "Hagåtña",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Chamorro"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 549,
    tld: ".gu",
  },
  gw: {
    name: "Guinea-Bissau",
    capital: "Bissau",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["Portuguese"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 36125,
    tld: ".gw",
  },
  gy: {
    name: "Guyana",
    capital: "Georgetown",
    continent: "South America",
    subregion: "South America",
    languages: ["English"],
    currency: { name: "Guyanese Dollar", code: "GYD", symbol: "$" },
    areaKm2: 214969,
    tld: ".gy",
  },
  hk: {
    name: "Hong Kong",
    altNames: ["Hong Kong", "Hong Kong SAR", "Hong Kong, China"],
    capital: "Hong Kong",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Cantonese", "English"],
    currency: { name: "Hong Kong Dollar", code: "HKD", symbol: "$" },
    areaKm2: 1104,
    tld: ".hk",
  },
  hn: {
    name: "Honduras",
    capital: "Tegucigalpa",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Honduran Lempira", code: "HNL", symbol: "L" },
    areaKm2: 112492,
    tld: ".hn",
  },
  hr: {
    name: "Croatia",
    capital: "Zagreb",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Croatian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 56594,
    tld: ".hr",
  },
  ht: {
    name: "Haiti",
    capital: "Port-au-Prince",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Haitian Creole", "French"],
    currency: { name: "Haitian Gourde", code: "HTG", symbol: "G" },
    areaKm2: 27750,
    tld: ".ht",
  },
  hu: {
    name: "Hungary",
    capital: "Budapest",
    continent: "Europe",
    subregion: "Central Europe",
    languages: ["Hungarian"],
    currency: { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
    areaKm2: 93028,
    tld: ".hu",
  },
  id: {
    name: "Indonesia",
    capital: "Jakarta",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Indonesian"],
    currency: { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
    areaKm2: 1904569,
    tld: ".id",
  },
  ie: {
    name: "Ireland",
    capital: "Dublin",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Irish", "English"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 70273,
    tld: ".ie",
  },
  il: {
    name: "Israel",
    capital: "Jerusalem",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Hebrew", "Arabic"],
    currency: { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
    areaKm2: 22072,
    tld: ".il",
  },
  im: {
    name: "Isle of Man",
    capital: "Douglas",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Manx"],
    currency: { name: "Pound Sterling", code: "GBP", symbol: "£" },
    areaKm2: 572,
    tld: ".im",
  },
  in: {
    name: "India",
    capital: "New Delhi",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Hindi", "English"],
    currency: { name: "Indian Rupee", code: "INR", symbol: "₹" },
    areaKm2: 3287590,
    tld: ".in",
  },
  io: {
    name: "British Indian Ocean Territory",
    capital: "Camp Thunder Cove",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 60,
    tld: ".io",
  },
  iq: {
    name: "Iraq",
    capital: "Baghdad",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic", "Kurdish"],
    currency: { name: "Iraqi Dinar", code: "IQD", symbol: "ع.د" },
    areaKm2: 438317,
    tld: ".iq",
  },
  ir: {
    name: "Iran",
    altNames: [
      "Iran (Islamic Republic of)",
      "Iran",
      "Islamic Republic of Iran",
    ],
    capital: "Tehran",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Persian (Farsi)"],
    currency: { name: "Iranian Rial", code: "IRR", symbol: "﷼" },
    areaKm2: 1648195,
    tld: ".ir",
  },
  is: {
    name: "Iceland",
    capital: "Reykjavík",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Icelandic"],
    currency: { name: "Icelandic Króna", code: "ISK", symbol: "kr" },
    areaKm2: 103000,
    tld: ".is",
  },
  it: {
    name: "Italy",
    capital: "Rome",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 301340,
    tld: ".it",
  },
  je: {
    name: "Jersey",
    capital: "Saint Helier",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "French"],
    currency: { name: "Pound Sterling", code: "GBP", symbol: "£" },
    areaKm2: 118,
    tld: ".je",
  },
  jm: {
    name: "Jamaica",
    capital: "Kingston",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Jamaican Dollar", code: "JMD", symbol: "$" },
    areaKm2: 10991,
    tld: ".jm",
  },
  jo: {
    name: "Jordan",
    capital: "Amman",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
    areaKm2: 89342,
    tld: ".jo",
  },
  jp: {
    name: "Japan",
    capital: "Tokyo",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Japanese"],
    currency: { name: "Japanese Yen", code: "JPY", symbol: "¥" },
    areaKm2: 377975,
    tld: ".jp",
  },
  ke: {
    name: "Kenya",
    capital: "Nairobi",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Swahili", "English"],
    currency: { name: "Kenyan Shilling", code: "KES", symbol: "Sh" },
    areaKm2: 580367,
    tld: ".ke",
  },
  kg: {
    name: "Kyrgyzstan",
    capital: "Bishkek",
    continent: "Asia",
    subregion: "Central Asia",
    languages: ["Kyrgyz", "Russian"],
    currency: { name: "Kyrgyzstani Som", code: "KGS", symbol: "с" },
    areaKm2: 199951,
    tld: ".kg",
  },
  kh: {
    name: "Cambodia",
    capital: "Phnom Penh",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Khmer"],
    currency: { name: "Cambodian Riel", code: "KHR", symbol: "៛" },
    areaKm2: 181035,
    tld: ".kh",
  },
  ki: {
    name: "Kiribati",
    capital: "Tarawa",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Gilbertese"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 811,
    tld: ".ki",
  },
  km: {
    name: "Comoros",
    capital: "Moroni",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Comorian", "French", "Arabic"],
    currency: { name: "Comorian Franc", code: "KMF", symbol: "Fr" },
    areaKm2: 1862,
    tld: ".km",
  },
  kn: {
    name: "Saint Kitts and Nevis",
    capital: "Basseterre",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 261,
    tld: ".kn",
  },
  kp: {
    name: "North Korea",
    altNames: [
      "Korea (Democratic People's Republic of)",
      "North Korea",
      "Democratic People's Republic of Korea",
      "DPRK",
    ],
    capital: "Pyongyang",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Korean"],
    currency: { name: "North Korean Won", code: "KPW", symbol: "₩" },
    areaKm2: 120538,
    tld: ".kp",
  },
  kr: {
    name: "South Korea",
    altNames: [
      "Korea (Republic of)",
      "South Korea",
      "Republic of Korea",
      "ROK",
    ],
    capital: "Seoul",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Korean"],
    currency: { name: "South Korean Won", code: "KRW", symbol: "₩" },
    areaKm2: 100210,
    tld: ".kr",
  },
  kw: {
    name: "Kuwait",
    capital: "Kuwait City",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
    areaKm2: 17818,
    tld: ".kw",
  },
  ky: {
    name: "Cayman Islands",
    capital: "George Town",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Cayman Islands Dollar", code: "KYD", symbol: "$" },
    areaKm2: 264,
    tld: ".ky",
  },
  kz: {
    name: "Kazakhstan",
    capital: "Astana",
    continent: "Asia",
    subregion: "Central Asia",
    languages: ["Kazakh", "Russian"],
    currency: { name: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
    areaKm2: 2724900,
    tld: ".kz",
  },
  la: {
    name: "Laos",
    altNames: ["Lao People's Democratic Republic", "Laos"],
    capital: "Vientiane",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Lao"],
    currency: { name: "Lao Kip", code: "LAK", symbol: "₭" },
    areaKm2: 236800,
    tld: ".la",
  },
  lb: {
    name: "Lebanon",
    capital: "Beirut",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Lebanese Pound", code: "LBP", symbol: "ل.ل." },
    areaKm2: 10452,
    tld: ".lb",
  },
  lc: {
    name: "Saint Lucia",
    capital: "Castries",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 616,
    tld: ".lc",
  },
  li: {
    name: "Liechtenstein",
    capital: "Vaduz",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["German"],
    currency: { name: "Swiss Franc", code: "CHF", symbol: "Fr." },
    areaKm2: 160,
    tld: ".li",
  },
  lk: {
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Sinhala", "Tamil"],
    currency: { name: "Sri Lankan Rupee", code: "LKR", symbol: "Rs" },
    areaKm2: 65610,
    tld: ".lk",
  },
  lr: {
    name: "Liberia",
    capital: "Monrovia",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Liberian Dollar", code: "LRD", symbol: "$" },
    areaKm2: 111369,
    tld: ".lr",
  },
  ls: {
    name: "Lesotho",
    capital: "Maseru",
    continent: "Africa",
    subregion: "Southern Africa",
    languages: ["Sesotho", "English"],
    currency: { name: "Lesotho Loti", code: "LSL", symbol: "L" },
    areaKm2: 30355,
    tld: ".ls",
  },
  lt: {
    name: "Lithuania",
    capital: "Vilnius",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Lithuanian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 65300,
    tld: ".lt",
  },
  lu: {
    name: "Luxembourg",
    capital: "Luxembourg City",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["Luxembourgish", "French", "German"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 2586,
    tld: ".lu",
  },
  lv: {
    name: "Latvia",
    capital: "Riga",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Latvian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 64559,
    tld: ".lv",
  },
  ly: {
    name: "Libya",
    altNames: ["Libyan Arab Jamahiriya"],
    capital: "Tripoli",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    currency: { name: "Libyan Dinar", code: "LYD", symbol: "ل.د" },
    areaKm2: 1759540,
    tld: ".ly",
  },
  ma: {
    name: "Morocco",
    capital: "Rabat",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic", "Berber"],
    currency: { name: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
    areaKm2: 446550,
    tld: ".ma",
  },
  mc: {
    name: "Monaco",
    capital: "Monaco",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 2.02,
    tld: ".mc",
  },
  md: {
    name: "Moldova",
    capital: "Chișinău",
    altNames: ["Republic of", "Moldova", "Republic of Moldova"],
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Romanian"],
    currency: { name: "Moldovan Leu", code: "MDL", symbol: "L" },
    areaKm2: 33846,
    tld: ".md",
  },
  me: {
    name: "Montenegro",
    capital: "Podgorica",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Montenegrin"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 13812,
    tld: ".me",
  },
  mf: {
    name: "Saint Martin",
    altNames: ["Saint Martin_(island)", "France"],
    capital: "Marigot",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["French", "English"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 53,
    tld: ".mf",
  },
  mg: {
    name: "Madagascar",
    capital: "Antananarivo",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Malagasy", "French"],
    currency: { name: "Malagasy Ariary", code: "MGA", symbol: "Ar" },
    areaKm2: 587041,
    tld: ".mg",
  },
  mh: {
    name: "Marshall Islands",
    capital: "Majuro",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["Marshallese", "English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 181,
    tld: ".mh",
  },
  mk: {
    name: "North Macedonia",
    altNames: ["Republic of North Macedonia"],
    capital: "Skopje",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Macedonian"],
    currency: { name: "Macedonian Denar", code: "MKD", symbol: "ден" },
    areaKm2: 25713,
    tld: ".mk",
  },
  ml: {
    name: "Mali",
    capital: "Bamako",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 1240192,
    tld: ".ml",
  },
  mm: {
    name: "Myanmar",
    altNames: ["Myanmar", "Burma"],
    capital: "Naypyidaw",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Burmese"],
    currency: { name: "Myanmar Kyat", code: "MMK", symbol: "Ks" },
    areaKm2: 676578,
    tld: ".mm",
  },
  mn: {
    name: "Mongolia",
    capital: "Ulaanbaatar",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Mongolian"],
    currency: { name: "Mongolian Tögrög", code: "MNT", symbol: "₮" },
    areaKm2: 1564110,
    tld: ".mn",
  },
  mo: {
    name: "Macau",
    capital: "Macau",
    altNames: [
      "Macao",
      "Macau",
      "Macao SAR",
      "Macau SAR",
      "Macao, China",
      "Macau, China",
    ],
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Cantonese", "Portuguese"],
    currency: { name: "Macanese Pataca", code: "MOP", symbol: "P" },
    areaKm2: 30,
    tld: ".mo",
  },
  mp: {
    name: "Northern Mariana Islands",
    capital: "Saipan",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["English", "Chamorro", "Carolinian"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 464,
    tld: ".mp",
  },
  mq: {
    name: "Martinique",
    capital: "Fort-de-France",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 1128,
    tld: ".mq",
  },
  mr: {
    name: "Mauritania",
    capital: "Nouakchott",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["Arabic"],
    currency: { name: "Mauritanian Ouguiya", code: "MRU", symbol: "UM" },
    areaKm2: 1030700,
    tld: ".mr",
  },
  ms: {
    name: "Montserrat",
    capital: "Brades (de facto), Plymouth (de jure)",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 102,
    tld: ".ms",
  },
  mt: {
    name: "Malta",
    capital: "Valletta",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Maltese", "English"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 316,
    tld: ".mt",
  },
  mu: {
    name: "Mauritius",
    capital: "Port Louis",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "French"],
    currency: { name: "Mauritian Rupee", code: "MUR", symbol: "₨" },
    areaKm2: 2040,
    tld: ".mu",
  },
  mv: {
    name: "Maldives",
    capital: "Malé",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Dhivehi"],
    currency: { name: "Maldivian Rufiyaa", code: "MVR", symbol: ".ރ" },
    areaKm2: 300,
    tld: ".mv",
  },
  mw: {
    name: "Malawi",
    capital: "Lilongwe",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Chichewa", "English"],
    currency: { name: "Malawian Kwacha", code: "MWK", symbol: "MK" },
    areaKm2: 118484,
    tld: ".mw",
  },
  mx: {
    name: "Mexico",
    capital: "Mexico City",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Mexican Peso", code: "MXN", symbol: "$" },
    areaKm2: 1972550,
    tld: ".mx",
  },
  my: {
    name: "Malaysia",
    capital: "Kuala Lumpur",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Malay"],
    currency: { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
    areaKm2: 330803,
    tld: ".my",
  },
  mz: {
    name: "Mozambique",
    capital: "Maputo",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Portuguese"],
    currency: { name: "Mozambican Metical", code: "MZN", symbol: "MT" },
    areaKm2: 801590,
    tld: ".mz",
  },
  na: {
    name: "Namibia",
    capital: "Windhoek",
    continent: "Africa",
    subregion: "Southern Africa",
    languages: ["English"],
    currency: { name: "Namibian Dollar", code: "NAD", symbol: "$" },
    areaKm2: 825615,
    tld: ".na",
  },
  nc: {
    name: "New Caledonia",
    capital: "Nouméa",
    continent: "Oceania",
    subregion: "Melanesia",
    languages: ["French"],
    currency: { name: "CFP Franc", code: "XPF", symbol: "Fr" },
    areaKm2: 18575,
    tld: ".nc",
  },
  ne: {
    name: "Niger",
    capital: "Niamey",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 1267000,
    tld: ".ne",
  },
  nf: {
    name: "Norfolk Island",
    capital: "Kingston",
    continent: "Oceania",
    subregion: "Australia and New Zealand",
    languages: ["English", "Norfuk"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 36,
    tld: ".nf",
  },
  ng: {
    name: "Nigeria",
    capital: "Abuja",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
    areaKm2: 923768,
    tld: ".ng",
  },
  ni: {
    name: "Nicaragua",
    capital: "Managua",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Nicaraguan Córdoba", code: "NIO", symbol: "C$" },
    areaKm2: 130373,
    tld: ".ni",
  },
  nl: {
    name: "Netherlands",
    capital: "Amsterdam",
    continent: "Europe",
    subregion: "Western Europe",
    languages: ["Dutch"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 41850,
    tld: ".nl",
  },
  no: {
    name: "Norway",
    capital: "Oslo",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Norwegian"],
    currency: { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
    areaKm2: 323802,
    tld: ".no",
  },
  np: {
    name: "Nepal",
    capital: "Kathmandu",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Nepali"],
    currency: { name: "Nepalese Rupee", code: "NPR", symbol: "₨" },
    areaKm2: 147181,
    tld: ".np",
  },
  nr: {
    name: "Nauru",
    capital: "Yaren (de facto)",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["Nauruan", "English"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 21,
    tld: ".nr",
  },
  nu: {
    name: "Niue",
    capital: "Alofi",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Niuean", "English"],
    currency: { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    areaKm2: 260,
    tld: ".nu",
  },
  nz: {
    name: "New Zealand",
    capital: "Wellington",
    continent: "Oceania",
    subregion: "Australia and New Zealand",
    languages: ["English", "Māori", "NZ Sign Language"],
    currency: { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    areaKm2: 268838,
    tld: ".nz",
  },
  om: {
    name: "Oman",
    capital: "Muscat",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Omani Rial", code: "OMR", symbol: "ر.ع." },
    areaKm2: 309500,
    tld: ".om",
  },
  pa: {
    name: "Panama",
    capital: "Panama City",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "Panamanian Balboa", code: "PAB", symbol: "B/." },
    areaKm2: 75417,
    tld: ".pa",
  },
  pe: {
    name: "Peru",
    capital: "Lima",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Peruvian Sol", code: "PEN", symbol: "S/." },
    areaKm2: 1285216,
    tld: ".pe",
  },
  pf: {
    name: "French Polynesia",
    capital: "Papeete",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["French", "Tahitian"],
    currency: { name: "CFP Franc", code: "XPF", symbol: "Fr" },
    areaKm2: 4167,
    tld: ".pf",
  },
  pg: {
    name: "Papua New Guinea",
    capital: "Port Moresby",
    continent: "Oceania",
    subregion: "Melanesia",
    languages: ["Tok Pisin", "English", "Hiri Motu"],
    currency: { name: "Papua New Guinean Kina", code: "PGK", symbol: "K" },
    areaKm2: 462840,
    tld: ".pg",
  },
  ph: {
    name: "Philippines",
    capital: "Manila",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Filipino", "English"],
    currency: { name: "Philippine Peso", code: "PHP", symbol: "₱" },
    areaKm2: 342353,
    tld: ".ph",
  },
  pk: {
    name: "Pakistan",
    capital: "Islamabad",
    continent: "Asia",
    subregion: "Southern Asia",
    languages: ["Urdu", "English"],
    currency: { name: "Pakistani Rupee", code: "PKR", symbol: "₨" },
    areaKm2: 881912,
    tld: ".pk",
  },
  pl: {
    name: "Poland",
    capital: "Warsaw",
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Polish"],
    currency: { name: "Polish Złoty", code: "PLN", symbol: "zł" },
    areaKm2: 312679,
    tld: ".pl",
  },
  pm: {
    name: "Saint Pierre and Miquelon",
    altNames: ["St. Pierre and Miquelon"],
    capital: "Saint-Pierre",
    continent: "North America",
    subregion: "Northern America",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 242,
    tld: ".pm",
  },
  pn: {
    name: "Pitcairn Islands",
    capital: "Adamstown",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Pitkern", "English"],
    currency: { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    areaKm2: 47,
    tld: ".pn",
  },
  pr: {
    name: "Puerto Rico",
    capital: "San Juan",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Spanish", "English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 8870,
    tld: ".pr",
  },
  ps: {
    name: "Palestine",
    capital: "Jerusalem (claimed), Ramallah (de facto)",
    altNames: [
      "Palestine, State of",
      "Palestine",
      "State of Palestine",
      "Occupied Palestinian Territory",
      "West Bank and Gaza",
    ],
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Israeli New Shekel", code: "ILS", symbol: "₪" },
    areaKm2: 6220,
    tld: ".ps",
  },
  pt: {
    name: "Portugal",
    capital: "Lisbon",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Portuguese"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 92226,
    tld: ".pt",
  },
  pw: {
    name: "Palau",
    capital: "Ngerulmud",
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["Palauan", "English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 459,
    tld: ".pw",
  },
  py: {
    name: "Paraguay",
    capital: "Asunción",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish", "Guaraní"],
    currency: { name: "Paraguayan Guaraní", code: "PYG", symbol: "₲" },
    areaKm2: 406752,
    tld: ".py",
  },
  qa: {
    name: "Qatar",
    capital: "Doha",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Qatari Riyal", code: "QAR", symbol: "ر.ق" },
    areaKm2: 11586,
    tld: ".qa",
  },
  re: {
    name: "Réunion",
    altNames: ["Reunion"],
    capital: "Saint-Denis",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 2511,
    tld: ".re",
  },
  ro: {
    name: "Romania",
    capital: "Bucharest",
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Romanian"],
    currency: { name: "Romanian Leu", code: "RON", symbol: "lei" },
    areaKm2: 238391,
    tld: ".ro",
  },
  rs: {
    name: "Serbia",
    capital: "Belgrade",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Serbian"],
    currency: { name: "Serbian Dinar", code: "RSD", symbol: "дин." },
    areaKm2: 88361,
    tld: ".rs",
  },
  ru: {
    name: "Russia",
    altNames: ["Russian Federation"],
    continent: "Europe",
    capital: "Moscow",
    languages: ["Russian"],
    currency: { name: "Russian Ruble", code: "RUB", symbol: "₽" },
    areaKm2: 17098242,
    tld: ".ru",
  },
  rw: {
    name: "Rwanda",
    capital: "Kigali",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Kinyarwanda", "French", "English", "Swahili"],
    currency: { name: "Rwandan Franc", code: "RWF", symbol: "Fr" },
    areaKm2: 26338,
    tld: ".rw",
  },
  sa: {
    name: "Saudi Arabia",
    capital: "Riyadh",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Saudi Riyal", code: "SAR", symbol: "ر.س" },
    areaKm2: 2149690,
    tld: ".sa",
  },
  sb: {
    name: "Solomon Islands",
    capital: "Honiara",
    continent: "Oceania",
    subregion: "Melanesia",
    languages: ["English"],
    currency: { name: "Solomon Islands Dollar", code: "SBD", symbol: "$" },
    areaKm2: 28896,
    tld: ".sb",
  },
  sc: {
    name: "Seychelles",
    capital: "Victoria",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Seychellois Creole", "English", "French"],
    currency: { name: "Seychellois Rupee", code: "SCR", symbol: "₨" },
    areaKm2: 452,
    tld: ".sc",
  },
  sd: {
    name: "Sudan",
    capital: "Khartoum",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic", "English"],
    currency: { name: "Sudanese Pound", code: "SDG", symbol: "ج.س." },
    areaKm2: 1861484,
    tld: ".sd",
  },
  se: {
    name: "Sweden",
    capital: "Stockholm",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Swedish"],
    currency: { name: "Swedish Krona", code: "SEK", symbol: "kr" },
    areaKm2: 450295,
    tld: ".se",
  },
  sg: {
    name: "Singapore",
    capital: "Singapore",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Malay", "Mandarin", "English", "Tamil"],
    currency: { name: "Singapore Dollar", code: "SGD", symbol: "$" },
    areaKm2: 710,
    tld: ".sg",
  },
  sh: {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    altNames: [
      "Saint Helena, Ascension & Tristan da Cunha",
      "Saint Helena",
      "Ascension Island",
      "Tristan da Cunha",
      "St Helena",
      "St. Helena",
    ],
    capital: "Jamestown (Saint Helena)",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Saint Helena Pound", code: "SHP", symbol: "£" },
    areaKm2: 394,
    tld: ".sh",
  },
  si: {
    name: "Slovenia",
    capital: "Ljubljana",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Slovene"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 20273,
    tld: ".si",
  },
  sj: {
    name: "Svalbard and Jan Mayen",
    altNames: ["Svalbard & Jan Mayen", "Norway"],
    capital: "Longyearbyen",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["Norwegian"],
    currency: { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
    areaKm2: 61022,
    tld: ".sj",
  },
  sk: {
    name: "Slovakia",
    capital: "Bratislava",
    continent: "Europe",
    subregion: "Central Europe",
    languages: ["Slovak"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 49035,
    tld: ".sk",
  },
  sl: {
    name: "Sierra Leone",
    capital: "Freetown",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["English"],
    currency: { name: "Sierra Leonean Leone", code: "SLL", symbol: "Le" },
    areaKm2: 71740,
    tld: ".sl",
  },
  sm: {
    name: "San Marino",
    capital: "San Marino",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 61,
    tld: ".sm",
  },
  sn: {
    name: "Senegal",
    capital: "Dakar",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 196722,
    tld: ".sn",
  },
  so: {
    name: "Somalia",
    capital: "Mogadishu",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Somali", "Arabic"],
    currency: { name: "Somali Shilling", code: "SOS", symbol: "Sh" },
    areaKm2: 637657,
    tld: ".so",
  },
  sr: {
    name: "Suriname",
    capital: "Paramaribo",
    continent: "South America",
    subregion: "South America",
    languages: ["Dutch"],
    currency: { name: "Surinamese Dollar", code: "SRD", symbol: "$" },
    areaKm2: 163820,
    tld: ".sr",
  },
  ss: {
    name: "South Sudan",
    capital: "Juba",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["English"],
    currency: { name: "South Sudanese Pound", code: "SSP", symbol: "£" },
    areaKm2: 644329,
    tld: ".ss",
  },
  st: {
    name: "São Tomé and Príncipe",
    altNames: ["Sao Tome and Principe", "Sao Tome", "Sao Tome & Principe"],
    capital: "São Tomé",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["Portuguese"],
    currency: {
      name: "São Tomé and Príncipe Dobra",
      code: "STN",
      symbol: "Db",
    },
    areaKm2: 964,
    tld: ".st",
  },
  sv: {
    name: "El Salvador",
    capital: "San Salvador",
    continent: "North America",
    subregion: "Central America",
    languages: ["Spanish"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 21041,
    tld: ".sv",
  },
  sx: {
    name: "Sint Maarten",
    capital: "Philipsburg",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["Dutch", "English"],
    currency: {
      name: "Netherlands Antillean Guilder",
      code: "ANG",
      symbol: "ƒ",
    },
    areaKm2: 34,
    tld: ".sx",
  },
  sy: {
    name: "Syria",
    altNames: ["Syrian Arab Republic"],
    capital: "Damascus",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Syrian Pound", code: "SYP", symbol: "£" },
    areaKm2: 185180,
    tld: ".sy",
  },
  sz: {
    name: "Eswatini (Swaziland)",
    altNames: ["Eswatini", "Kingdom of Eswatini", "Swaziland"],
    capital: "Mbabane (administrative), Lobamba (royal and legislative)",
    continent: "Africa",
    subregion: "Southern Africa",
    languages: ["Swazi", "English"],
    currency: { name: "Eswatini Lilangeni", code: "SZL", symbol: "L" },
    areaKm2: 17364,
    tld: ".sz",
  },
  tc: {
    name: "Turks and Caicos Islands",
    capital: "Cockburn Town",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 948,
    tld: ".tc",
  },
  td: {
    name: "Chad",
    capital: "N'Djamena",
    continent: "Africa",
    subregion: "Middle Africa",
    languages: ["Arabic", "French"],
    currency: { name: "Central African CFA Franc", code: "XAF", symbol: "Fr" },
    areaKm2: 1284000,
    tld: ".td",
  },
  tf: {
    name: "French Southern and Antarctic Lands",
    capital: "Saint-Pierre",
    continent: "Antarctica",
    subregion: "Antarctica",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 439672,
    tld: ".tf",
  },
  tg: {
    name: "Togo",
    capital: "Lomé",
    continent: "Africa",
    subregion: "Western Africa",
    languages: ["French"],
    currency: { name: "West African CFA Franc", code: "XOF", symbol: "Fr" },
    areaKm2: 56785,
    tld: ".tg",
  },
  th: {
    name: "Thailand",
    capital: "Bangkok",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Thai"],
    currency: { name: "Thai Baht", code: "THB", symbol: "฿" },
    areaKm2: 513120,
    tld: ".th",
  },
  tj: {
    name: "Tajikistan",
    capital: "Dushanbe",
    continent: "Asia",
    subregion: "Central Asia",
    languages: ["Tajik", "Russian"],
    currency: { name: "Tajikistani Somoni", code: "TJS", symbol: "ЅМ" },
    areaKm2: 143100,
    tld: ".tj",
  },
  tk: {
    name: "Tokelau",
    capital: "Nukunonu (administrative)",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Tokelauan", "English"],
    currency: { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
    areaKm2: 12,
    tld: ".tk",
  },
  tl: {
    name: "Timor-Leste",
    altNames: ["East Timor"],
    capital: "Dili",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Tetum", "Portuguese"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 14874,
    tld: ".tl",
  },
  tm: {
    name: "Turkmenistan",
    capital: "Ashgabat",
    continent: "Asia",
    subregion: "Central Asia",
    languages: ["Turkmen", "Russian"],
    currency: { name: "Turkmenistani Manat", code: "TMT", symbol: "m" },
    areaKm2: 488100,
    tld: ".tm",
  },
  tn: {
    name: "Tunisia",
    capital: "Tunis",
    continent: "Africa",
    subregion: "Northern Africa",
    languages: ["Arabic"],
    currency: { name: "Tunisian Dinar", code: "TND", symbol: "د.ت" },
    areaKm2: 163610,
    tld: ".tn",
  },
  to: {
    name: "Tonga",
    capital: "Nukuʻalofa",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Tongan", "English"],
    currency: { name: "Tongan Paʻanga", code: "TOP", symbol: "T$" },
    areaKm2: 748,
    tld: ".to",
  },
  tr: {
    name: "Turkey",
    capital: "Ankara",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Turkish"],
    currency: { name: "Turkish Lira", code: "TRY", symbol: "₺" },
    areaKm2: 783562,
    tld: ".tr",
  },
  tt: {
    name: "Trinidad and Tobago",
    capital: "Port of Spain",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Trinidad and Tobago Dollar", code: "TTD", symbol: "$" },
    areaKm2: 5130,
    tld: ".tt",
  },
  tv: {
    name: "Tuvalu",
    capital: "Funafuti",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Tuvaluan", "English"],
    currency: { name: "Australian Dollar", code: "AUD", symbol: "$" },
    areaKm2: 26,
    tld: ".tv",
  },
  tw: {
    name: "Taiwan",
    altNames: ["Republic of China", "Chinese Taipei"],
    capital: "Taipei",
    continent: "Asia",
    subregion: "Eastern Asia",
    languages: ["Mandarin"],
    currency: { name: "New Taiwan Dollar", code: "TWD", symbol: "NT$" },
    areaKm2: 36193,
    tld: ".tw",
  },
  tz: {
    name: "Tanzania",
    altNames: ["Tanzania, United Republic of"],
    capital: "Dodoma",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Swahili", "English"],
    currency: { name: "Tanzanian Shilling", code: "TZS", symbol: "Sh" },
    areaKm2: 945087,
    tld: ".tz",
  },
  ua: {
    name: "Ukraine",
    capital: "Kyiv",
    continent: "Europe",
    subregion: "Eastern Europe",
    languages: ["Ukrainian"],
    currency: { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
    areaKm2: 603500,
    tld: ".ua",
  },
  ug: {
    name: "Uganda",
    capital: "Kampala",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["English", "Luganda", "Swahili"],
    currency: { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
    areaKm2: 241551,
    tld: ".ug",
  },
  us: {
    name: "United States of America",
    altNames: ["United States", "USA", "U.S.A.", "US", "U.S.", "America"],
    capital: "Washington, D.C.",
    continent: "North America",
    subregion: "Northern America",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 9833517,
    tld: ".us",
  },
  uy: {
    name: "Uruguay",
    capital: "Montevideo",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Uruguayan Peso", code: "UYU", symbol: "$" },
    areaKm2: 176215,
    tld: ".uy",
  },
  uz: {
    name: "Uzbekistan",
    capital: "Tashkent",
    continent: "Asia",
    subregion: "Central Asia",
    languages: ["Uzbek", "Russian"],
    currency: { name: "Uzbekistani Soʻm", code: "UZS", symbol: "лв" },
    areaKm2: 447400,
    tld: ".uz",
  },
  va: {
    name: "Vatican City",
    altNames: [
      "Holy See (Vatican City State)",
      "Holy See",
      "Vatican City State",
      "Vatican City",
      "Vatican",
    ],
    capital: "Vatican City",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Italian", "Latin"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 0.44,
    tld: ".va",
  },
  vc: {
    name: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "Eastern Caribbean Dollar", code: "XCD", symbol: "$" },
    areaKm2: 389,
    tld: ".vc",
  },
  ve: {
    name: "Venezuela",
    altNames: [
      "Venezuela (Bolivarian Republic of)",
      "Bolivarian Republic of Venezuela",
    ],
    capital: "Caracas",
    continent: "South America",
    subregion: "South America",
    languages: ["Spanish"],
    currency: { name: "Venezuelan Bolívar", code: "VES", symbol: "Bs.S" },
    areaKm2: 916445,
    tld: ".ve",
  },
  vg: {
    name: "British Virgin Islands",
    capital: "Road Town",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 151,
    tld: ".vg",
  },
  vi: {
    name: "United States Virgin Islands",
    capital: "Charlotte Amalie",
    continent: "North America",
    subregion: "Caribbean",
    languages: ["English"],
    currency: { name: "United States Dollar", code: "USD", symbol: "$" },
    areaKm2: 347,
    tld: ".vi",
  },
  vn: {
    name: "Vietnam",
    altNames: ["Viet Nam"],
    capital: "Hanoi",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    languages: ["Vietnamese"],
    currency: { name: "Vietnamese Đồng", code: "VND", symbol: "₫" },
    areaKm2: 331212,
    tld: ".vn",
  },
  vu: {
    name: "Vanuatu",
    capital: "Port Vila",
    continent: "Oceania",
    subregion: "Melanesia",
    languages: ["Bislama", "English", "French"],
    currency: { name: "Vanuatu Vatu", code: "VUV", symbol: "Vt" },
    areaKm2: 12189,
    tld: ".vu",
  },
  wf: {
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["French", "Wallisian", "Futunan"],
    currency: { name: "CFP Franc", code: "XPF", symbol: "Fr" },
    areaKm2: 142,
    tld: ".wf",
  },
  ws: {
    name: "Samoa",
    capital: "Apia",
    continent: "Oceania",
    subregion: "Polynesia",
    languages: ["Samoan", "English"],
    currency: { name: "Samoan Tālā", code: "WST", symbol: "T" },
    areaKm2: 2842,
    tld: ".ws",
  },
  xk: {
    name: "Kosovo",
    capital: "Pristina",
    continent: "Europe",
    subregion: "Southern Europe",
    languages: ["Albanian", "Serbian"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 10908,
    tld: ".xk",
  },
  ye: {
    name: "Yemen",
    capital: "Sana'a (de jure), Aden (temporary capital)",
    continent: "Asia",
    subregion: "Western Asia",
    languages: ["Arabic"],
    currency: { name: "Yemeni Rial", code: "YER", symbol: "﷼" },
    areaKm2: 527968,
    tld: ".ye",
  },
  yt: {
    name: "Mayotte",
    capital: "Mamoudzou",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["French"],
    currency: { name: "Euro", code: "EUR", symbol: "€" },
    areaKm2: 374,
    tld: ".yt",
  },
  za: {
    name: "South Africa",
    capital:
      "Pretoria (executive), Cape Town (legislative), Bloemfontein (judicial)",
    continent: "Africa",
    subregion: "Southern Africa",
    languages: [
      "Afrikaans",
      "English",
      "Ndebele",
      "Northern Sotho",
      "Southern Sotho",
      "Swazi",
      "Tsonga",
      "Tswana",
      "Venda",
      "Xhosa",
      "Zulu",
    ],
    currency: { name: "South African Rand", code: "ZAR", symbol: "R" },
    areaKm2: 1221037,
    tld: ".za",
  },
  zm: {
    name: "Zambia",
    capital: "Lusaka",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["English"],
    currency: { name: "Zambian Kwacha", code: "ZMW", symbol: "ZK" },
    areaKm2: 752612,
    tld: ".zm",
  },
  zw: {
    name: "Zimbabwe",
    capital: "Harare",
    continent: "Africa",
    subregion: "Eastern Africa",
    languages: ["Shona", "Ndebel//e", "English"],
    currency: { name: "Zimbabwean Dollar", code: "ZWL", symbol: "Z$" },
    areaKm2: 390757,
    tld: ".zw",
  },
  "gb-sct": {
    name: "Scotland",
    capital: "Edinburgh",
    altNames: ["Scot"],
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Scottish Gaelic", "Scots"],
    currency: {
      name: "Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
    areaKm2: 77933,
    tld: ".uk",
  },
  "gb-wls": {
    name: "Wales",
    capital: "Cardiff",
    altNames: ["Cymru"],
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Welsh"],
    currency: {
      name: "Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
    areaKm2: 20779,
    tld: ".uk",
  },
  "gb-nir": {
    name: "Northern Ireland",
    capital: "Belfast",
    altNames: ["NI"],
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English", "Irish", "Ulster Scots"],
    currency: {
      name: "Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
    areaKm2: 14130,
    tld: ".uk",
  },
  "gb-eng": {
    name: "England",
    capital: "London",
    continent: "Europe",
    subregion: "Northern Europe",
    languages: ["English"],
    currency: {
      name: "Pound Sterling",
      code: "GBP",
      symbol: "£",
    },
    areaKm2: 130395,
    tld: ".uk",
  },
  um: {
    name: "United States Minor Outlying Islands",
    capital: "Washington, D.C. (administrative)",
    altNames: [
      "US Minor Outlying Islands",
      "UM",
      "USMOI",
      "United States",
      "USA",
      "U.S.A.",
      "US",
      "U.S.",
      "America",
    ],
    continent: "Oceania",
    subregion: "Micronesia",
    languages: ["English"],
    currency: {
      name: "United States Dollar",
      code: "USD",
      symbol: "$",
    },
    areaKm2: 34.2,
    tld: ".um (retired in 2007)",
  },
  hm: {
    name: "Heard Island and McDonald Islands",
    altNames: ["Heard Island & McDonald Islands", "HIMI", "Australia"],
    continent: "Antarctica",
    languages: ["English"],
    currency: {
      name: "Australian Dollar",
      code: "AUD",
      symbol: "$",
    },
    areaKm2: 368,
    tld: ".hm",
  },
  bv: {
    name: "Bouvet Island",
    altNames: ["Bouvetøya", "Norway"],
    continent: "Antarctica",
    areaKm2: 49,
    tld: ".bv",
  },
} as const;

// Helper function to check if a country is UN recognized
export const isUNCountry = (countryCode: string): boolean => {
  return UN_COUNTRIES.includes(countryCode as any);
};

export const ALTNAME_USE_COUNTRY = ["ge", "mf", "ci"];

export const SAMEFLAG_COUNTRY = {
  sj: "Norwegian archipelago",
  mf: "Overseas collectivity of France",
  um: "Groups of islands under U.S jurisdiction",
  hm: "Uninhabited islands in the Southern Ocean ",
  bv: "Uninhabited subantarctic volcanic island",
};

export // Default quiz length
const DEFAULT_QUIZ_LENGTH = 10;
export const DEFAULT_COUNTRY_FILTER: CountryFilter = "un";

// Add constants for the total counts
export const TOTAL_UN_COUNTRIES = 195;
export const TOTAL_ALL_COUNTRIES = Object.keys(COUNTRY_DATA).length;


export const DisplayModes = [
  "capital",
  "languages",
  "areaKm2",
  "tld",
  "currency",
];

export const DisplayModeLables = {
  capital: "Capital City",
  languages: "Official Languages",
  areaKm2: "Area(Km²)",
  tld: "Top Level Domain",
  currency: "Currency",
};